apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: image-build-cron-trigger
spec:
  schedule: "*/5 * * * *"
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: trigger
            env:
            - name: SINK_URL
              value: el-image-builder.default.svc.cluster.local:8080
            - name: GIT_REPOSITORY
              value: github.com/tektoncd/plumbing
            - name: GIT_REVISION
              value: master
            - name: TARGET_IMAGE
              value: gcr.io/s390x-test/tekton-releases/dogfooding/skopeo:latest
            - name: CONTEXT_PATH
              value: tekton/images/skopeo
            - name: PLATFORMS
              value: "linux/amd64,linux/s390x,linux/ppc64le,linux/arm64"
