apiVersion: triggers.tekton.dev/v1alpha1
kind: EventListener
metadata:
  name: test-nightly
spec:
  serviceAccountName: tekton-test-nightly
  triggers:
  - name: pipeline-nightly-test-trigger-s390x
    interceptors:
    - cel:
        filter: >-
          'trigger-template' in body &&
           body['trigger-template'] == 'pipeline' &&
           'arch' in body.params.target &&
           body.params.target.arch == 's390x'
    bindings:
    - ref: trigger-to-deploy-test-tekton-project
    template:
      name: tekton-pipeline-nightly-test-s390x
---
apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerBinding
metadata:
  name: trigger-to-deploy-test-tekton-project
spec:
  params:
  - name: namespace
    value: $(body.params.run.namespace)
  - name: containerRegistry
    value: $(body.params.target.registry)
  - name: targetArch
    value: $(body.params.target.arch)
  - name: remoteSecret
    value: $(body.params.remote.secret)
  - name: remoteHost
    value: $(body.params.remote.host)
  - name: remotePort
    value: $(body.params.remote.port)
  - name: remoteUser
    value: $(body.params.remote.user)
