namespace: default
commonAnnotations:
  managed-by: Tekton

resources:
- images
- org-permissions/peribolos.yaml
- org-permissions/peribolos-trigger.yaml
- release
- cd
- ci
- nightly-release
- nightly-tests
