apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: deploy-tekton-project-nightly
spec:
  params:
  - name: package
    description: package to install
  - name: container-registry
    description: container registry used to publish build images
  - name: target-arch
    description: target architecture for tests (s390x, ppc64le, arm64)
  workspaces:
  - name: k8s-shared
    description: workspace for k8s config, configuration file is expected to have `config` name
    mountPath: /root/.kube
  - name: source-code
    description: workspace with source code for tekton component
    mountPath: /workspace
  steps:
  - name: deploy
    workingdir: $(workspaces.source-code.path)/src/$(params.package)
    image: gcr.io/tekton-releases/dogfooding/test-runner:latest
    env:
    - name: KO_DOCKER_REPO
      value: $(params.container-registry)
    - name: KUBECONFIG
      value: $(workspaces.k8s-shared.path)/config
    command:
    - /bin/bash
    args:
    - -ce
    - |
      ko apply --platform=linux/$(params.target-arch) -f config/
      kubectl wait -n tekton-pipelines --for=condition=ready pods --all --timeout=120s
